# Generated from native source055 cold qualification reader requests; no scientific execution.
# Native trace SHA256 06b7f2cea97cb68f53039998e376fc4e7c22442a513a14261d911efc58cb9b92
@compile_workload begin
    if WannierNLQG.FIRST_USE_WORKLOAD_ENABLED
        precompile(
            Tuple{
                typeof(Base.Core.kwcall),
                NamedTuple{(:task_selection,), Tuple{Nothing}},
                typeof(WannierNLQGOperatorBundleExt._scientific_content_digest),
                Symbol,
                Array{WannierNLQG.Core.RealSpaceOperatorKind, 1},
                Array{Float64, 2},
                Array{Int64, 2},
                Array{Int64, 1},
                Array{String, 1},
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                Bool,
                String,
                String,
                String,
                String,
                String,
                String,
                Nothing,
                Vararg{String, 8},
            },
        )
        precompile(
            Tuple{
                typeof(_operator_bundle_first_use_call),
                typeof(Base.Core.kwcall),
                NamedTuple{(:task_selection,), Tuple{Nothing}},
                typeof(WannierNLQGOperatorBundleExt._scientific_content_digest),
                Symbol,
                Array{WannierNLQG.Core.RealSpaceOperatorKind, 1},
                Array{Float64, 2},
                Array{Int64, 2},
                Array{Int64, 1},
                Array{String, 1},
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                Bool,
                String,
                String,
                String,
                String,
                String,
                String,
                Nothing,
                Vararg{String, 8},
            },
        )
        precompile(
            Tuple{
                Type{WannierNLQG.IO.OperatorBundleManifest},
                String,
                Symbol,
                Array{WannierNLQG.Core.RealSpaceOperatorKind, 1},
                Int64,
                Array{Float64, 2},
                Array{Int64, 2},
                Array{Int64, 1},
                Array{WannierNLQG.IO.OperatorBundleIndexEntry, 1},
                Int64,
                String,
                String,
                String,
                Array{Float64, 2},
                Array{Float64, 2},
                Array{Float64, 2},
                Array{Float64, 2},
                Symbol,
                Symbol,
                Bool,
                Bool,
                Tuple{Int64, Int64, Int64},
                Float64,
                Int64,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                Bool,
                Bool,
                String,
                String,
                String,
                Int64,
                Int64,
                Int64,
                Int64,
                Float64,
                Float64,
                String,
                String,
                String,
                Nothing,
                String,
                String,
                String,
                Float64,
                Float64,
                Float64,
                Bool,
                Float64,
                Float64,
                Bool,
                Float64,
                Float64,
                Float64,
                Float64,
                Bool,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Bool,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                Bool,
                Bool,
                Bool,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                Nothing,
                String,
                String,
                Nothing,
                String,
                Base.Dict{String, Any},
                String,
                String,
                String,
                Bool,
                String,
                String,
                Bool,
                String,
                String,
                String,
                String,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                String,
                Array{String, 1},
                String,
                String,
                String,
                String,
                String,
                Nothing,
                Nothing,
            },
        )
        precompile(
            Tuple{
                typeof(_operator_bundle_first_use_call),
                Type{WannierNLQG.IO.OperatorBundleManifest},
                String,
                Symbol,
                Array{WannierNLQG.Core.RealSpaceOperatorKind, 1},
                Int64,
                Array{Float64, 2},
                Array{Int64, 2},
                Array{Int64, 1},
                Array{WannierNLQG.IO.OperatorBundleIndexEntry, 1},
                Int64,
                String,
                String,
                String,
                Array{Float64, 2},
                Array{Float64, 2},
                Array{Float64, 2},
                Array{Float64, 2},
                Symbol,
                Symbol,
                Bool,
                Bool,
                Tuple{Int64, Int64, Int64},
                Float64,
                Int64,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                Bool,
                Bool,
                String,
                String,
                String,
                Int64,
                Int64,
                Int64,
                Int64,
                Float64,
                Float64,
                String,
                String,
                String,
                Nothing,
                String,
                String,
                String,
                Float64,
                Float64,
                Float64,
                Bool,
                Float64,
                Float64,
                Bool,
                Float64,
                Float64,
                Float64,
                Float64,
                Bool,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Bool,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                Bool,
                Bool,
                Bool,
                String,
                String,
                String,
                String,
                String,
                String,
                String,
                Nothing,
                String,
                String,
                Nothing,
                String,
                Base.Dict{String, Any},
                String,
                String,
                String,
                Bool,
                String,
                String,
                Bool,
                String,
                String,
                String,
                String,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                Nothing,
                String,
                Array{String, 1},
                String,
                String,
                String,
                String,
                String,
                Nothing,
                Nothing,
            },
        )
        @assert !WannierNLQG.MPI.Initialized()
    end
end
