const QE_PAW_SPN_SCHEMA = "wanniernlqg.qe-paw-spn"
const QE_PAW_SPN_SCHEMA_VERSION = "1.0"
const QE_PAW_SPN_ALGORITHM_VERSION = "pw2wannier90-compute-spin-paw-q0-v3-frame-contract-bound"

"""Measure Hermiticity and diagonal-imaginary residuals of a QE SPN tensor."""
function _qe_paw_spn_diagnostics(data)
    hermiticity = 0.0
    diagonal_imaginary = 0.0
    for kpoint in axes(data, 4), component in axes(data, 3)
        matrix = @view data[:, :, component, kpoint]
        hermiticity = max(hermiticity, maximum(abs, matrix - matrix'; init = 0.0))
        diagonal_imaginary = max(diagonal_imaginary, maximum(abs, imag.(diag(matrix)); init = 0.0))
    end
    return hermiticity, diagonal_imaginary
end

"""
Generate a QE PAW/USPP-aware Wannier90 SPN file from the same full-cutoff
spinor coefficients and q=0 augmentation metric used by the native MMN/uIu
backend.  The contraction follows QE `pw2wannier90::compute_spin`; an optional
upstream SPN is validation-only and never supplies matrix elements.
"""
function generate_qe_paw_spn(
    source::QuantumEspressoWavefunctionSource,
    topology_file::AbstractString;
    output_spn_file::AbstractString,
    provenance_json::AbstractString = output_spn_file * ".provenance.json",
    oracle_spn_file::Union{Nothing, AbstractString} = nothing,
    thresholds::VASPPAWSPNThresholds = VASPPAWSPNThresholds(),
    require_oracle::Bool = false,
    formatted::Bool = false,
    overwrite::Bool = false,
    max_cached_wavefunction_kpoints::Int = 8,
)
    isempty(strip(output_spn_file)) && throw(ArgumentError("output_spn_file must not be empty"))
    isempty(strip(provenance_json)) && throw(ArgumentError("provenance_json must not be empty"))
    source.band_range === nothing ||
        throw(ArgumentError("QE_NNKP_BAND_AUTHORITY_REQUIRED: source.band_range must be nothing"))
    source.representation_cutoff_ev === nothing || throw(
        ArgumentError("QE_PAW_SPN_FULL_CUTOFF_REQUIRED: representation_cutoff_ev must be nothing"),
    )
    require_oracle &&
        oracle_spn_file === nothing &&
        throw(ArgumentError("QE_PAW_SPN_ORACLE_REQUIRED: oracle_spn_file is required"))
    output = abspath(output_spn_file)
    provenance = abspath(provenance_json)
    output == provenance && throw(ArgumentError("SPN output and provenance paths must differ"))
    ispath(output) && !overwrite && throw(ArgumentError("refusing to overwrite SPN: $(output)"))
    ispath(provenance) &&
        !overwrite &&
        throw(ArgumentError("refusing to overwrite SPN provenance: $(provenance)"))

    state = _uiu_qe_state(source, topology_file, max_cached_wavefunction_kpoints)
    state.native.spinor || throw(
        ArgumentError("QE_PAW_SPN_SPINOR_REQUIRED: noncollinear spinor coefficients are required"),
    )
    num_bands = state.topology.num_bands
    num_kpts = state.topology.num_kpts
    total = zeros(ComplexF64, num_bands, num_bands, 3, num_kpts)
    pseudo_maximum = 0.0
    augmentation_maximum = 0.0
    for kpoint in 1:num_kpts
        block, pseudo, augmentation = state.spn_block(kpoint)
        total[:, :, :, kpoint] .= block
        pseudo_maximum = max(pseudo_maximum, maximum(abs, pseudo; init = 0.0))
        augmentation_maximum = max(augmentation_maximum, maximum(abs, augmentation; init = 0.0))
    end
    hermiticity, diagonal_imaginary = _qe_paw_spn_diagnostics(total)
    spn = WannierSPN(num_bands, num_kpts, total)
    oracle =
        oracle_spn_file === nothing ? nothing :
        read_wannier_spn(something(oracle_spn_file); formatted)
    oracle === nothing ||
        size(oracle.data) == size(total) ||
        throw(ArgumentError("QE_PAW_SPN_ORACLE_MISMATCH: SPN dimensions differ"))
    oracle_parity = oracle === nothing ? nothing : _paw_array_parity(total, oracle.data)
    oracle_pass =
        oracle_parity !== nothing && _paw_metric_passes(
            something(oracle_parity),
            thresholds.oracle_max_absolute,
            thresholds.oracle_rms,
            thresholds.oracle_relative_l2,
        )
    passed =
        state.generalized_norm <= thresholds.generalized_norm_max_absolute &&
        hermiticity <= thresholds.hermiticity_max_absolute &&
        diagonal_imaginary <= thresholds.diagonal_imaginary_max_absolute &&
        (!require_oracle || oracle_pass) &&
        (oracle_parity === nothing || oracle_pass)
    oracle_status = oracle_parity === nothing ? "NOT_PROVIDED" : oracle_pass ? "PASS" : "FAIL"
    diagnostics = vcat(
        state.diagnostics,
        ["oracle_status=$(oracle_status)", "upstream_oracle=QE pw2wannier90 compute_spin"],
    )
    artifacts = Dict{String, String}("provenance_json" => provenance)
    if passed
        written = write_wannier_spn(
            output,
            spn;
            formatted,
            comment = "Generated by WannierNLQG QE PAW-SPN",
        )
        artifacts["spn"] = written
        artifacts["spn_sha256"] = sha256_file(written)
    elseif isfile(output) && overwrite
        rm(output; force = true)
    end
    oracle_spn_file === nothing || begin
        artifacts["oracle_spn"] = abspath(something(oracle_spn_file))
        artifacts["oracle_spn_sha256"] = sha256_file(something(oracle_spn_file))
    end
    input_sha256 = copy(state.input_sha256)
    kpoints_fractional = reduce(
        vcat,
        transpose(_uiu_kpoint_fractional(state.native, kpoint)) for kpoint in 1:num_kpts
    )
    frame_contract = _generation_band_gauge_contract(
        source,
        NativeDFTHamiltonian(),
        nothing,
        num_bands,
        num_kpts,
    )
    payload = Dict(
        "schema" => QE_PAW_SPN_SCHEMA,
        "schema_version" => QE_PAW_SPN_SCHEMA_VERSION,
        "algorithm_version" => QE_PAW_SPN_ALGORITHM_VERSION,
        "source_code" => "qe",
        "status" => passed ? "PASS" : "FAIL",
        "passed" => passed,
        "physical_metric" => "QE PAW/USPP q=0 pseudo plus augmentation",
        "spinor" => state.native.spinor,
        "num_bands" => num_bands,
        "num_kpoints" => num_kpts,
        "source_band_gauge" => NATIVE_DFT_BAND_GAUGE,
        "target_band_gauge" => NATIVE_DFT_BAND_GAUGE,
        "gauge_artifact_sha256" => "NOT_APPLICABLE",
        "band_frame_transform_sha256" => frame_contract.transform_sha256,
        "band_frame_contract_sha256" => frame_contract.contract_sha256,
        "band_frame_contract" => band_frame_contract_summary(frame_contract),
        "band_gauge_rotation_sha256" => frame_contract.transform_sha256,
        "band_gauge_rotation_semantics" => "legacy_alias_of_band_frame_transform_sha256",
        "kpoints_fractional" =>
            [collect(@view(kpoints_fractional[kpoint, :])) for kpoint in 1:num_kpts],
        "spin_components" => ["x", "y", "z"],
        "formatted" => formatted,
        "generalized_norm_max_absolute" => state.generalized_norm,
        "hermiticity_max_absolute" => hermiticity,
        "diagonal_imaginary_max_absolute" => diagonal_imaginary,
        "pseudo_max_absolute" => pseudo_maximum,
        "augmentation_max_absolute" => augmentation_maximum,
        "thresholds" => Dict(
            "generalized_norm_max_absolute" => thresholds.generalized_norm_max_absolute,
            "hermiticity_max_absolute" => thresholds.hermiticity_max_absolute,
            "diagonal_imaginary_max_absolute" => thresholds.diagonal_imaginary_max_absolute,
            "oracle_max_absolute" => thresholds.oracle_max_absolute,
            "oracle_rms" => thresholds.oracle_rms,
            "oracle_relative_l2" => thresholds.oracle_relative_l2,
        ),
        "oracle_parity" =>
            oracle_parity === nothing ? nothing :
            Dict(
                "max_absolute" => something(oracle_parity).max_absolute,
                "root_mean_square" => something(oracle_parity).root_mean_square,
                "relative_l2" => something(oracle_parity).relative_l2,
                "worst_index" => something(oracle_parity).worst_index,
                "finite" => something(oracle_parity).finite,
            ),
        "artifacts" => artifacts,
        "input_sha256" => input_sha256,
        "diagnostics" => diagnostics,
    )
    payload["contract_sha256"] = _spn_provenance_contract_sha256(
        payload["schema"],
        payload["schema_version"],
        payload["source_code"],
        payload["passed"],
        payload["source_band_gauge"],
        payload["target_band_gauge"],
        payload["band_frame_transform_sha256"],
        payload["band_frame_contract_sha256"],
        payload["num_bands"],
        payload["num_kpoints"],
        payload["physical_metric"],
        payload["spinor"],
        get(artifacts, "spn_sha256", "NOT_PUBLISHED"),
        input_sha256,
        kpoints_fractional,
    )
    payload["payload_sha256"] = _qe_spn_payload_sha256(payload)
    _uiu_atomic_json(provenance, payload)
    return QEPAWSPNResult(
        passed ? spn : nothing,
        oracle_parity,
        state.generalized_norm,
        hermiticity,
        diagonal_imaginary,
        passed,
        provenance,
        artifacts,
        input_sha256,
        diagnostics,
    )
end
