# Generated from actual cold TB qualification: Julia 1.11.2, parent source 505e52e260258d31a7ddf45b3e74d0b91d7ae4fbb2d5481e224a634228f88c1d
# Native trace SHA256 db3fdc30b14c2aa2c4bc739d77b0d8d911820ec3e7e5e27d08ef4f50b5fd5916
# This owner is actually active without Spglib; only compilation is performed.
# No scientific execution, file handles, communicator, or output is retained.
function _wannierization_entry_compile_call(
    function_value::F,
    arguments::Vararg{Any, N},
) where {F, N}
    return Base.@noinline function_value(arguments...)
end
@compile_workload begin
    if WannierizationInternalSupport.WannierNLQG.FIRST_USE_WORKLOAD_ENABLED
        let WannierNLQGWannierizationExt = @__MODULE__
            precompile(
                Tuple{
                    typeof(HDF5.generic_read),
                    HDF5.Attribute,
                    HDF5.Datatype,
                    Type{HDF5.FixedString{3351, 0}},
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(HDF5.generic_read),
                    HDF5.Attribute,
                    HDF5.Datatype,
                    Type{HDF5.FixedString{3351, 0}},
                },
            )
            precompile(
                Tuple{
                    typeof(WannierNLQGWannierizationExt.OperatorExport._qualification_wcc_residual),
                    Array{Float64, 2},
                    Array{Float64, 2},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(WannierNLQGWannierizationExt.OperatorExport._qualification_wcc_residual),
                    Array{Float64, 2},
                    Array{Float64, 2},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(
                        WannierNLQGWannierizationExt.OperatorExport._qualification_projection_idempotence,
                    ),
                    WannierNLQG.Core.RealSpaceOperator{3},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(
                        WannierNLQGWannierizationExt.OperatorExport._qualification_projection_idempotence,
                    ),
                    WannierNLQG.Core.RealSpaceOperator{3},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(
                        WannierNLQGWannierizationExt.OperatorExport._qualification_operator_difference,
                    ),
                    WannierNLQG.Core.RealSpaceOperator{3},
                    WannierNLQG.Core.RealSpaceOperator{3},
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(
                        WannierNLQGWannierizationExt.OperatorExport._qualification_operator_difference,
                    ),
                    WannierNLQG.Core.RealSpaceOperator{3},
                    WannierNLQG.Core.RealSpaceOperator{3},
                },
            )
            precompile(
                Tuple{
                    typeof(
                        WannierNLQGWannierizationExt.OperatorExport._qualification_projection_idempotence,
                    ),
                    WannierNLQG.Core.RealSpaceOperator{4},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(
                        WannierNLQGWannierizationExt.OperatorExport._qualification_projection_idempotence,
                    ),
                    WannierNLQG.Core.RealSpaceOperator{4},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(
                        WannierNLQGWannierizationExt.OperatorExport._qualification_operator_difference,
                    ),
                    WannierNLQG.Core.RealSpaceOperator{4},
                    WannierNLQG.Core.RealSpaceOperator{4},
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(
                        WannierNLQGWannierizationExt.OperatorExport._qualification_operator_difference,
                    ),
                    WannierNLQG.Core.RealSpaceOperator{4},
                    WannierNLQG.Core.RealSpaceOperator{4},
                },
            )
            precompile(
                Tuple{
                    typeof(WannierNLQG.SymmetryFoundation.maximum_real_space_covariance_error),
                    WannierNLQG.Core.RealSpaceOperator{4},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(WannierNLQG.SymmetryFoundation.maximum_real_space_covariance_error),
                    WannierNLQG.Core.RealSpaceOperator{4},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(Base.grow_to!),
                    Base.Dict{Tuple{Int64, Int64, Int64}, Int64},
                    Base.Generator{
                        Base.OneTo{Int64},
                        WannierNLQGWannierizationExt.OperatorExport.var"#319#321"{
                            WannierNLQG.Core.RealSpaceOperator{3},
                        },
                    },
                    Int64,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(Base.grow_to!),
                    Base.Dict{Tuple{Int64, Int64, Int64}, Int64},
                    Base.Generator{
                        Base.OneTo{Int64},
                        WannierNLQGWannierizationExt.OperatorExport.var"#319#321"{
                            WannierNLQG.Core.RealSpaceOperator{3},
                        },
                    },
                    Int64,
                },
            )
            precompile(
                Tuple{
                    typeof(Base.grow_to!),
                    Base.Dict{Tuple{Int64, Int64, Int64}, Int64},
                    Base.Generator{
                        Base.OneTo{Int64},
                        WannierNLQGWannierizationExt.OperatorExport.var"#320#322"{
                            WannierNLQG.Core.RealSpaceOperator{3},
                        },
                    },
                    Int64,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(Base.grow_to!),
                    Base.Dict{Tuple{Int64, Int64, Int64}, Int64},
                    Base.Generator{
                        Base.OneTo{Int64},
                        WannierNLQGWannierizationExt.OperatorExport.var"#320#322"{
                            WannierNLQG.Core.RealSpaceOperator{3},
                        },
                    },
                    Int64,
                },
            )
            precompile(
                Tuple{
                    typeof(WannierNLQG.SymmetryFoundation.symmetrize_real_space_operator),
                    WannierNLQG.Core.RealSpaceOperator{4},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(WannierNLQG.SymmetryFoundation.symmetrize_real_space_operator),
                    WannierNLQG.Core.RealSpaceOperator{4},
                    WannierNLQG.SymmetryFoundation.WannierSymmetryPlan,
                },
            )
            precompile(
                Tuple{
                    typeof(Base.grow_to!),
                    Base.Dict{Tuple{Int64, Int64, Int64}, Int64},
                    Base.Generator{
                        Base.OneTo{Int64},
                        WannierNLQGWannierizationExt.OperatorExport.var"#319#321"{
                            WannierNLQG.Core.RealSpaceOperator{4},
                        },
                    },
                    Int64,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(Base.grow_to!),
                    Base.Dict{Tuple{Int64, Int64, Int64}, Int64},
                    Base.Generator{
                        Base.OneTo{Int64},
                        WannierNLQGWannierizationExt.OperatorExport.var"#319#321"{
                            WannierNLQG.Core.RealSpaceOperator{4},
                        },
                    },
                    Int64,
                },
            )
            precompile(
                Tuple{
                    typeof(Base.grow_to!),
                    Base.Dict{Tuple{Int64, Int64, Int64}, Int64},
                    Base.Generator{
                        Base.OneTo{Int64},
                        WannierNLQGWannierizationExt.OperatorExport.var"#320#322"{
                            WannierNLQG.Core.RealSpaceOperator{4},
                        },
                    },
                    Int64,
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(Base.grow_to!),
                    Base.Dict{Tuple{Int64, Int64, Int64}, Int64},
                    Base.Generator{
                        Base.OneTo{Int64},
                        WannierNLQGWannierizationExt.OperatorExport.var"#320#322"{
                            WannierNLQG.Core.RealSpaceOperator{4},
                        },
                    },
                    Int64,
                },
            )
            precompile(
                Tuple{
                    typeof(Core.kwcall),
                    NamedTuple{
                        (
                            :authoritative_hamiltonian,
                            :authoritative_hamiltonian_sha256,
                            :energy_shift_qualification,
                            :maximum_energy_shift_audit_reference_ev,
                            :rms_energy_shift_audit_reference_ev,
                            :target_energy_shift_audit_status,
                            :symmetrized_parent_energy_shift_audit_status,
                            :residual_gate_phase,
                            :raw_preflight_diagnostic_status,
                            :native_difference_qualification,
                            :native_difference_audit_status,
                            :qualification_scope,
                            :target_anchor,
                            :target_complement_completion,
                            :target_complement_max_element_ev,
                            :auxiliary_parent_qualification,
                            :symmetrized_target_subspace_status,
                            :auxiliary_parent_audit_status,
                            :target_scope_production_eligible,
                            :target_leakage_semantics,
                            :target_leakage_formula_sha256,
                            :target_leakage_threshold,
                            :scoped_production_eligible,
                            :global_production_eligible,
                        ),
                        Tuple{
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            Bool,
                            String,
                            String,
                            Nothing,
                            Bool,
                            Bool,
                        },
                    },
                    Type{WannierNLQG.Wannierization.TBSymmetryQualification},
                    String,
                    String,
                    Array{WannierNLQG.Wannierization.TBSymmetryMetric, 1},
                },
            )
            precompile(
                Tuple{
                    typeof(_wannierization_entry_compile_call),
                    typeof(Core.kwcall),
                    NamedTuple{
                        (
                            :authoritative_hamiltonian,
                            :authoritative_hamiltonian_sha256,
                            :energy_shift_qualification,
                            :maximum_energy_shift_audit_reference_ev,
                            :rms_energy_shift_audit_reference_ev,
                            :target_energy_shift_audit_status,
                            :symmetrized_parent_energy_shift_audit_status,
                            :residual_gate_phase,
                            :raw_preflight_diagnostic_status,
                            :native_difference_qualification,
                            :native_difference_audit_status,
                            :qualification_scope,
                            :target_anchor,
                            :target_complement_completion,
                            :target_complement_max_element_ev,
                            :auxiliary_parent_qualification,
                            :symmetrized_target_subspace_status,
                            :auxiliary_parent_audit_status,
                            :target_scope_production_eligible,
                            :target_leakage_semantics,
                            :target_leakage_formula_sha256,
                            :target_leakage_threshold,
                            :scoped_production_eligible,
                            :global_production_eligible,
                        ),
                        Tuple{
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            String,
                            Bool,
                            String,
                            String,
                            Nothing,
                            Bool,
                            Bool,
                        },
                    },
                    Type{WannierNLQG.Wannierization.TBSymmetryQualification},
                    String,
                    String,
                    Array{WannierNLQG.Wannierization.TBSymmetryMetric, 1},
                },
            )
        end
        @assert !WannierNLQG.MPI.Initialized()
    end
end
