module Core

using LinearAlgebra

include("Constants.jl")
include("WannierCenterConventions.jl")
include("RealSpaceOperators.jl")
include("Models.jl")
include("Coordinates.jl")
include("CalculationUtils.jl")

export ELEMENTARY_CHARGE_C
export REDUCED_PLANCK_CONSTANT_J_S
export REDUCED_PLANCK_CONSTANT_EV_S
export BOLTZMANN_CONSTANT_EV_K
export COMPLEX_ZERO
export WannierCenterConvention, CONVENTION_I, CONVENTION_II
export wannier_center_convention_name
export TightBindingModel, KPointSpectrum
export RealSpaceOperatorKind, RealSpaceOperatorSymmetrySpec, RealSpaceOperator
export REAL_SPACE_OPERATOR_REGISTRY, REAL_SPACE_OPERATOR_CANONICAL_NAMES
export real_space_operator_name
export REAL_SPACE_HAMILTONIAN, REAL_SPACE_POSITION
export REAL_SPACE_HAMILTONIAN_WEIGHTED_CONNECTION
export REAL_SPACE_HAMILTONIAN_WEIGHTED_AXIAL_DERIVATIVE_OVERLAP
export REAL_SPACE_DERIVATIVE_OVERLAP_TENSOR, REAL_SPACE_AXIAL_DERIVATIVE_OVERLAP
export REAL_SPACE_SYMMETRIC_DERIVATIVE_OVERLAP, REAL_SPACE_SPIN
export REAL_SPACE_SPIN_TIMES_HAMILTONIAN, REAL_SPACE_SPIN_TIMES_POSITION
export REAL_SPACE_SPIN_TIMES_HAMILTONIAN_POSITION
export real_space_cartesian_to_fractional, reciprocal_cartesian_to_fractional
export reciprocal_lattice, finite_difference_step_matrix
export IntegralKGrid, KSliceGrid2D
export fermi_dirac, fermi_dirac!, gaussian_broadening, lorentzian_broadening
export select_band_window, has_active_transition
export validate_kslice_input, normalize_cartesian_indices
export integral_kpoint!, kslice_indices, kslice_kpoint!, make_kslice_grid, make_kslice_points
export normalize_band_selection,
    band_selection_flattened, band_selection_window, validate_band_selection
export validate_interband_band_selection
export normalize_triple_phase_product_band_selection, triple_phase_product_band_selection_flattened
export validate_triple_phase_product_band_selection
export normalize_target_band_group, normalize_target_band_groups
export validate_target_band_group, validate_target_band_groups
export band_group_output_label, real_kslice_band_groups_include_sum
export normalize_quantum_christoffel_band_selection, validate_quantum_christoffel_band_selection
export normalize_quantum_metric_dipole_band_selection, validate_quantum_metric_dipole_band_selection
export normalize_quantum_metric_quadrupole_band_selection,
    validate_quantum_metric_quadrupole_band_selection
export normalize_berry_curvature_dipole_band_selection,
    validate_berry_curvature_dipole_band_selection
export normalize_berry_curvature_quadrupole_band_selection,
    validate_berry_curvature_quadrupole_band_selection
export normalize_real_kslice_band_selection,
    normalize_berry_band_selection, normalize_quantum_metric_band_selection

end
