"""Formatted Wannier90 AMN data in `(band, wannier, kpoint)` storage order."""
struct WannierAMN
    num_bands::Int
    num_kpts::Int
    num_wannier::Int
    data::Array{ComplexF64, 3}

    function WannierAMN(num_bands, num_kpts, num_wannier, data)
        nb = Int(num_bands)
        nk = Int(num_kpts)
        nw = Int(num_wannier)
        nb > 0 || throw(ArgumentError("AMN num_bands must be positive"))
        nk > 0 || throw(ArgumentError("AMN num_kpts must be positive"))
        nw > 0 || throw(ArgumentError("AMN num_wannier must be positive"))
        values = Array{ComplexF64, 3}(data)
        size(values) == (nb, nw, nk) || throw(
            ArgumentError("AMN data has size $(size(values)); expected ($(nb), $(nw), $(nk))"),
        )
        all(isfinite, values) || throw(ArgumentError("AMN data contains NaN or Inf"))
        return new(nb, nk, nw, values)
    end
end

"""
    read_wannier_amn(filename) -> WannierAMN

Read a complete formatted Wannier90 `.amn` file. Indexed rows may appear in any
order, but duplicates, missing rows, non-finite coefficients, and out-of-range
indices fail before an object is returned.
"""
function read_wannier_amn(filename::AbstractString)::WannierAMN
    isfile(filename) || throw(ArgumentError("AMN file does not exist: $(filename)"))
    return open(filename, "r") do io
        eof(io) && throw(ArgumentError("AMN file is empty"))
        _ = readline(io)
        eof(io) && throw(ArgumentError("AMN dimension line is missing"))
        dimensions = parse.(Int, split(strip(readline(io))))
        length(dimensions) >= 3 || throw(ArgumentError("AMN dimension line is malformed"))
        num_bands, num_kpoints, num_wannier = dimensions[1:3]
        num_bands > 0 && num_kpoints > 0 && num_wannier > 0 ||
            throw(ArgumentError("AMN dimensions must be positive"))
        data = zeros(ComplexF64, num_bands, num_wannier, num_kpoints)
        filled = falses(num_bands, num_wannier, num_kpoints)
        for (offset, line) in enumerate(eachline(io))
            line_number = offset + 2
            tokens = split(strip(line))
            isempty(tokens) && continue
            length(tokens) >= 5 || throw(ArgumentError("AMN row $(line_number) is malformed"))
            band, wannier, kpoint = parse.(Int, tokens[1:3])
            1 <= band <= num_bands && 1 <= wannier <= num_wannier && 1 <= kpoint <= num_kpoints ||
                throw(ArgumentError("AMN row $(line_number) has an out-of-range index"))
            filled[band, wannier, kpoint] &&
                throw(ArgumentError("AMN contains a duplicate indexed row"))
            real_value = parse(Float64, replace(tokens[4], 'D' => 'E', 'd' => 'e'))
            imaginary_value = parse(Float64, replace(tokens[5], 'D' => 'E', 'd' => 'e'))
            isfinite(real_value) && isfinite(imaginary_value) ||
                throw(ArgumentError("AMN row $(line_number) contains NaN or Inf"))
            data[band, wannier, kpoint] = ComplexF64(real_value, imaginary_value)
            filled[band, wannier, kpoint] = true
        end
        all(filled) || throw(ArgumentError("AMN file is incomplete"))
        WannierAMN(num_bands, num_kpoints, num_wannier, data)
    end
end

"""
    write_wannier_amn(filename, amn; comment="Generated by WannierNLQG")

Atomically write standard formatted AMN rows with 17 significant digits. The
temporary file is created beside the destination so publication is one rename.
"""
function write_wannier_amn(
    filename::AbstractString,
    amn::WannierAMN;
    comment::AbstractString = "Generated by WannierNLQG",
)
    path = abspath(filename)
    mkpath(dirname(path))
    temporary, io = mktemp(dirname(path); cleanup = false)
    published = false
    try
        println(io, String(comment))
        @printf(io, "%d %d %d\n", amn.num_bands, amn.num_kpts, amn.num_wannier)
        for kpoint in 1:amn.num_kpts, wannier in 1:amn.num_wannier, band in 1:amn.num_bands
            value = amn.data[band, wannier, kpoint]
            @printf(
                io,
                "%5d %5d %5d % .17g % .17g\n",
                band,
                wannier,
                kpoint,
                real(value),
                imag(value),
            )
        end
        flush(io)
        close(io)
        mv(temporary, path; force = true)
        published = true
    finally
        isopen(io) && close(io)
        !published && isfile(temporary) && rm(temporary; force = true)
    end
    return path
end
