"""
    write_wannier_mmn(filename, mmn; comment="Generated by WannierNLQG")

Atomically write a formatted Wannier90 MMN file. `mmn.data[n,m,ib,k]`
retains the reader's band-index convention; the writer emits the reciprocal
`m,n` loop order required by the formatted protocol. No normalization or gauge
transformation is performed at this I/O boundary.
"""
function write_wannier_mmn(
    filename::AbstractString,
    mmn::WannierMMN;
    comment::AbstractString = "Generated by WannierNLQG",
)
    path = abspath(filename)
    mkpath(dirname(path))
    temporary, io = mktemp(dirname(path); cleanup = false)
    published = false
    try
        println(io, String(comment))
        @printf(io, "%d %d %d\n", mmn.num_bands, mmn.num_kpts, mmn.num_neighbors)
        for kpoint in 1:mmn.num_kpts, neighbor_index in 1:mmn.num_neighbors
            @printf(
                io,
                "%5d %5d %5d %5d %5d\n",
                kpoint,
                mmn.neighbors[neighbor_index, kpoint],
                mmn.reciprocal_shifts[1, neighbor_index, kpoint],
                mmn.reciprocal_shifts[2, neighbor_index, kpoint],
                mmn.reciprocal_shifts[3, neighbor_index, kpoint],
            )
            for m in 1:mmn.num_bands, n in 1:mmn.num_bands
                value = mmn.data[n, m, neighbor_index, kpoint]
                @printf(io, "% .17g % .17g\n", real(value), imag(value))
            end
        end
        flush(io)
        close(io)
        mv(temporary, path; force = true)
        published = true
    finally
        isopen(io) && close(io)
        !published && isfile(temporary) && rm(temporary; force = true)
    end
    return path
end
