"""Hamiltonian-only Wannier90 `_hr.dat` payload in R-last storage."""
struct WannierHR
    num_orbitals::Int
    num_r_vectors::Int
    r_degeneracies::Vector{Int}
    r_vectors::Matrix{Int}
    hamiltonian_r::Array{ComplexF64, 3}

    function WannierHR(num_orbitals, num_r_vectors, r_degeneracies, r_vectors, hamiltonian_r)
        nw = Int(num_orbitals)
        nr = Int(num_r_vectors)
        degeneracies = Int.(r_degeneracies)
        vectors = Matrix{Int}(r_vectors)
        values = Array{ComplexF64, 3}(hamiltonian_r)
        nw > 0 && nr > 0 || throw(ArgumentError("WannierHR dimensions must be positive"))
        length(degeneracies) == nr && all(>(0), degeneracies) ||
            throw(ArgumentError("WannierHR degeneracies are invalid"))
        size(vectors) == (3, nr) || throw(ArgumentError("WannierHR R vectors are invalid"))
        size(values) == (nw, nw, nr) ||
            throw(ArgumentError("WannierHR Hamiltonian dimensions are invalid"))
        all(isfinite, values) || throw(ArgumentError("WannierHR contains NaN or Inf"))
        return new(nw, nr, degeneracies, vectors, values)
    end
end

# Print Wannier90 degeneracies in rows of at most fifteen entries.
function _write_hr_degeneracies(io::Base.IO, degeneracies::Vector{Int})
    for first_index in 1:15:length(degeneracies)
        last_index = min(first_index + 14, length(degeneracies))
        for value in @view degeneracies[first_index:last_index]
            @printf(io, "%5d", value)
        end
        println(io)
    end
    return nothing
end

"""Atomically write a standard Hamiltonian-only Wannier90 `_hr.dat` file."""
function write_wannier_hr(
    filename::AbstractString,
    hamiltonian::WannierHR;
    comment::AbstractString = "Generated by WannierNLQG gauge-aware symmetrization",
    overwrite::Bool = false,
)
    path = abspath(filename)
    ispath(path) && !overwrite && throw(ArgumentError("refusing to overwrite HR file: $(path)"))
    mkpath(dirname(path))
    temporary, io = mktemp(dirname(path); cleanup = false)
    published = false
    try
        println(io, join(split(String(comment)), ' '))
        println(io, hamiltonian.num_orbitals)
        println(io, hamiltonian.num_r_vectors)
        _write_hr_degeneracies(io, hamiltonian.r_degeneracies)
        for r_index in 1:hamiltonian.num_r_vectors,
            column in 1:hamiltonian.num_orbitals,
            row in 1:hamiltonian.num_orbitals

            value = hamiltonian.hamiltonian_r[row, column, r_index]
            @printf(
                io,
                "%5d%5d%5d%5d%5d%22.14e%22.14e\n",
                hamiltonian.r_vectors[:, r_index]...,
                row,
                column,
                real(value),
                imag(value),
            )
        end
        flush(io)
        close(io)
        mv(temporary, path; force = true)
        published = true
    finally
        isopen(io) && close(io)
        !published && isfile(temporary) && rm(temporary; force = true)
    end
    return path
end

"""Read a complete standard Wannier90 `_hr.dat` file with indexed-row checks."""
function read_wannier_hr(filename::AbstractString)
    isfile(filename) || throw(ArgumentError("HR file does not exist: $(filename)"))
    return open(filename, "r") do io
        eof(io) && throw(ArgumentError("HR file is empty"))
        _ = readline(io)
        nw = parse(Int, strip(readline(io)))
        nr = parse(Int, strip(readline(io)))
        degeneracies = Int[]
        while length(degeneracies) < nr
            append!(degeneracies, parse.(Int, split(strip(readline(io)))))
        end
        length(degeneracies) == nr || throw(ArgumentError("HR degeneracy block is malformed"))
        vectors = Matrix{Int}(undef, 3, nr)
        values = zeros(ComplexF64, nw, nw, nr)
        filled = falses(nw, nw, nr)
        vector_to_index = Dict{NTuple{3, Int}, Int}()
        for line in eachline(io)
            tokens = split(strip(line))
            isempty(tokens) && continue
            length(tokens) >= 7 || throw(ArgumentError("HR indexed row is malformed"))
            r = (parse(Int, tokens[1]), parse(Int, tokens[2]), parse(Int, tokens[3]))
            row = parse(Int, tokens[4])
            column = parse(Int, tokens[5])
            1 <= row <= nw && 1 <= column <= nw ||
                throw(ArgumentError("HR orbital index is out of range"))
            r_index = get!(vector_to_index, r, length(vector_to_index) + 1)
            r_index <= nr || throw(ArgumentError("HR contains too many distinct R vectors"))
            vectors[:, r_index] .= r
            filled[row, column, r_index] && throw(ArgumentError("HR contains a duplicate row"))
            values[row, column, r_index] = ComplexF64(
                parse(Float64, replace(tokens[6], 'D' => 'E', 'd' => 'e')),
                parse(Float64, replace(tokens[7], 'D' => 'E', 'd' => 'e')),
            )
            filled[row, column, r_index] = true
        end
        length(vector_to_index) == nr && all(filled) ||
            throw(ArgumentError("HR file is incomplete"))
        WannierHR(nw, nr, degeneracies, vectors, values)
    end
end
