# Write Wannier90 degeneracies in rows of at most fifteen integers.
function _write_wannier_degeneracies(io::Base.IO, degeneracies::Vector{Int})
    for start in 1:15:length(degeneracies)
        stop = min(start + 14, length(degeneracies))
        for value in @view degeneracies[start:stop]
            @printf(io, "%5d", value)
        end
        println(io)
    end
    return nothing
end

"""
Write a complete Wannier90-compatible `_tb.dat` model.

The writer preserves the model's row-lattice and real-space-last Julia layout.
Hamiltonian/position values are written in the existing model's serialized
convention; degeneracy division remains owned by Fourier interpolation. The
destination is never overwritten unless requested.
"""
function write_wannier_tb(
    filename::AbstractString,
    model::TightBindingModel;
    comment::AbstractString = "Generated by WannierNLQG",
    overwrite::Bool = false,
)
    ispath(filename) &&
        !overwrite &&
        throw(ArgumentError("refusing to overwrite existing TB file: $(filename)"))
    parent = dirname(abspath(filename))
    mkpath(parent)
    open(filename, "w") do io
        println(io, join(split(String(comment)), ' '))
        for row in 1:3
            @printf(io, "%22.14e%22.14e%22.14e\n", model.lattice[row, :]...)
        end
        println(io, model.num_orbitals)
        println(io, model.num_r_vectors)
        _write_wannier_degeneracies(io, model.r_degeneracies)
        for r_index in 1:model.num_r_vectors
            println(io)
            @printf(io, "%5d%5d%5d\n", model.r_vectors[:, r_index]...)
            for column in 1:model.num_orbitals, row in 1:model.num_orbitals
                value = model.hamiltonian_r[row, column, r_index]
                @printf(io, "%5d%5d%22.14e%22.14e\n", row, column, real(value), imag(value))
            end
        end
        for r_index in 1:model.num_r_vectors
            println(io)
            @printf(io, "%5d%5d%5d\n", model.r_vectors[:, r_index]...)
            for column in 1:model.num_orbitals, row in 1:model.num_orbitals
                @printf(io, "%5d%5d", row, column)
                for cartesian in 1:3
                    value = model.position_r[row, column, cartesian, r_index]
                    @printf(io, "%22.14e%22.14e", real(value), imag(value))
                end
                println(io)
            end
        end
    end
    return String(filename)
end
