"""Return the canonical deterministic sort key for one stored group operation."""
_group_operation_key(operation) = (
    operation.antiunitary ? 1 : 0,
    Tuple(vec(operation.rotation_fractional)),
    Tuple(operation.translation_fractional),
    operation.source_index,
)

"""Return the maximum componentwise residual modulo lattice translations."""
function _periodic_translation_residual(left, right)
    delta = left .- right
    delta .-= round.(delta)
    return maximum(abs, delta)
end

"""Format one fractional translation component in a compact canonical form."""
function _fraction_string(value::Real, tolerance::Real)
    wrapped = mod(Float64(value), 1.0)
    (
        isapprox(wrapped, 0.0; atol = tolerance, rtol = 0.0) ||
        isapprox(wrapped, 1.0; atol = tolerance, rtol = 0.0)
    ) && return "0"
    rational = rationalize(Int, wrapped; tol = Float64(tolerance))
    denominator(rational) <= 192 || return string(wrapped)
    return denominator(rational) == 1 ? string(numerator(rational)) :
           "$(numerator(rational))/$(denominator(rational))"
end

"""Return the crystallographic order of an exact integer rotation matrix."""
function _integer_matrix_order(rotation::Matrix{Int})
    power = Matrix{Int}(I, 3, 3)
    for order in 1:12
        power *= rotation
        power == Matrix{Int}(I, 3, 3) && return order
    end
    error("fractional rotation has no crystallographic order <= 12")
end

"""Return a compact standard symbol for a unitary or antiunitary point operation."""
function _standard_operation_symbol(rotation::Matrix{Int}, antiunitary::Bool)
    determinant = round(Int, det(rotation))
    symbol = if determinant == 1
        string(_integer_matrix_order(rotation))
    elseif rotation == -Matrix{Int}(I, 3, 3)
        "-1"
    elseif _integer_matrix_order(rotation) == 2 && tr(rotation) == 1
        "m"
    else
        "-" * string(_integer_matrix_order(-rotation))
    end
    return antiunitary ? symbol * "'" : symbol
end

"""Construct exact identity, inverse, and multiplication tables for a finite group."""
function _finite_group_tables(operations; seitz::Bool, tolerance::Float64)
    ordered = sort(collect(operations); by = _group_operation_key)
    isempty(ordered) && error("cannot generate an empty symmetry group")
    n = length(ordered)
    product_table = zeros(Int, n, n)
    for left in 1:n, right in 1:n
        rotation = ordered[left].rotation_fractional * ordered[right].rotation_fractional
        translation = if seitz
            mod.(
                ordered[left].rotation_fractional * ordered[right].translation_fractional .+
                ordered[left].translation_fractional,
                1.0,
            )
        else
            zeros(3)
        end
        antiunitary = xor(ordered[left].antiunitary, ordered[right].antiunitary)
        matches = Int[]
        for candidate in 1:n
            operation = ordered[candidate]
            operation.antiunitary == antiunitary || continue
            operation.rotation_fractional == rotation || continue
            (
                !seitz ||
                _periodic_translation_residual(operation.translation_fractional, translation) <=
                tolerance
            ) || continue
            push!(matches, candidate)
        end
        length(matches) == 1 ||
            error("symmetry group product $(left)*$(right) has $(length(matches)) matches")
        product_table[left, right] = only(matches)
    end
    identities = findall(1:n) do index
        operation = ordered[index]
        !operation.antiunitary &&
            operation.rotation_fractional == Matrix{Int}(I, 3, 3) &&
            (
                !seitz ||
                _periodic_translation_residual(operation.translation_fractional, zeros(3)) <=
                tolerance
            )
    end
    length(identities) == 1 || error("symmetry group must contain one unitary identity")
    return ordered, product_table, only(identities)
end

"""Return the group indices generated by a selected set of operation indices."""
function _generated_group_indices(generators, product_table, identity)
    closed = Set([identity; collect(generators)])
    changed = true
    while changed
        changed = false
        current = sort!(collect(closed))
        for left in current, right in current
            product = product_table[left, right]
            if !(product in closed)
                push!(closed, product)
                changed = true
            end
        end
    end
    return closed
end

"""
Return a deterministic irredundant generating set and verify exact reconstruction.

For Seitz operations, translations are compared modulo lattice translations using
the artifact tolerance. The algorithm is canonical-order greedy followed by a
deterministic reverse redundancy pass; it does not claim globally minimum size.
"""
function response_group_generators(operations; seitz::Bool, tolerance::Real = 1.0e-8)
    tol = Float64(tolerance)
    isfinite(tol) && tol > 0 || throw(ArgumentError("group tolerance must be positive"))
    ordered, product_table, identity = _finite_group_tables(operations; seitz, tolerance = tol)
    generators = Int[]
    generated = _generated_group_indices(generators, product_table, identity)
    for candidate in eachindex(ordered)
        candidate == identity && continue
        candidate in generated && continue
        push!(generators, candidate)
        generated = _generated_group_indices(generators, product_table, identity)
    end
    length(generated) == length(ordered) || error("generator closure did not reconstruct group")
    for position in reverse(eachindex(generators))
        trial = [generators[index] for index in eachindex(generators) if index != position]
        length(_generated_group_indices(trial, product_table, identity)) == length(ordered) &&
            deleteat!(generators, position)
    end
    generated = _generated_group_indices(generators, product_table, identity)
    length(generated) == length(ordered) || error("irredundant generator closure failed")
    payload = Dict{String, Any}[]
    for (sequence, index) in enumerate(generators)
        operation = ordered[index]
        push!(
            payload,
            Dict(
                "sequence" => sequence,
                "kind" => operation.antiunitary ? "ANTIUNITARY" : "UNITARY",
                "operation_symbol" => _standard_operation_symbol(
                    operation.rotation_fractional,
                    operation.antiunitary,
                ),
                "rotation_fractional" =>
                    [[operation.rotation_fractional[row, column] for column in 1:3] for row in 1:3],
                "translation_fractional" => collect(operation.translation_fractional),
                "translation_fractional_rational" =>
                    [_fraction_string(value, tol) for value in operation.translation_fractional],
                "antiunitary" => operation.antiunitary,
                "source_operation_index" => operation.source_index,
            ),
        )
    end
    return Dict(
        "definition" =>
            seitz ? "finite Seitz operations modulo lattice translations" :
            "fractional point operations with antiunitary parity",
        "algorithm" => "canonical-order greedy irredundant; not globally minimum",
        "group_order" => length(ordered),
        "unitary_operation_count" => count(operation -> !operation.antiunitary, ordered),
        "antiunitary_operation_count" => count(operation -> operation.antiunitary, ordered),
        "generator_count" => length(payload),
        "generators" => payload,
        "closure_verified" => true,
        "reconstructed_group_order" => length(generated),
    )
end
