"""
Qualified, non-exported integration API consumed by sibling workflow layers.

Entries in this tuple are stable cross-layer contracts. Helpers absent from the
tuple remain private to `SymmetryFoundation` and must not be imported by other
modules, scripts, examples, or tests.
"""
const SYMMETRY_FOUNDATION_INTEGRATION_API = (
    :BOHR_TO_ANGSTROM,
    :DEFAULT_MAXIMUM_CARTESIAN_ROTATION_CORRECTION,
    :EFFECTIVE_CARTESIAN_ROTATION_TOLERANCE,
    :HARTREE_TO_EV,
    :SYMMETRY_FOUNDATION_INTEGRATION_API,
    :VASPWavecarHeader,
    :band_representation_schema_version,
    :build_band_product_table,
    :build_canonical_band_representation,
    :build_canonical_kpoint_action,
    :canonical_band_block_labels,
    :canonical_band_operation_key,
    :canonical_irreducible_star_plan,
    :canonical_plane_wave_sewing_matrix,
    :configure_band_qualification_window!,
    :detect_tb_compatibility_symmetry_operations,
    :group_invariant_cartesian_rotation_data,
    :infer_mp_grid,
    :is_identity_group_representation,
    :magnetic_point_group_catalog_entry,
    :magnetic_point_group_catalog_provenance,
    :magnetic_point_group_operation_identity,
    :magnetic_moments_sha256,
    :normalize_plane_wave_coefficients,
    :plane_wave_energy_ev,
    :qualification_mask_sha256,
    :read_band_representation_preparation_hdf5,
    :read_poscar_structure,
    :read_values_at,
    :read_vasp_wavecar_header,
    :read_vasp_wavefunctions,
    :resolve_cartesian_rotation_policy,
    :resolve_spglib_symprec_angstrom,
    :response_group_generators,
    :response_symmetry_group_report,
    :r_vector_key,
    :row_major_matrix,
    :selected_band_range,
    :sha256_file,
    :spin_action_matrix,
    :symmetry_detection_backend_provenance,
    :validate_authoritative_hamiltonian_key,
    :validate_band_representation,
    :validate_canonical_antiunitary_channel,
    :validate_public_band_representation_contract,
    :validate_unified_representation_mode_contract,
    :validate_vasp_magnetic_moment_sources,
    :write_band_representation_summary,
)
